### ISSUE TITLE
Ignore the IDE and temp files

### ISSUE THREAD

**Issue by tobegit3hub** [shekkizh/TensorflowProjects#2]
You should ignore the IDE files like [.idea](https://github.com/shekkizh/TensorflowProjects/tree/master/.idea), and the temp file like [FaceDetection.py~](https://github.com/shekkizh/TensorflowProjects/blob/master/FaceDetection/FaceDetection.py~) .

It will increase the size of project so that we need more time to pull. Please add these in `.gitignore`.

**Comment by shekkizh** [comment]
Removed files. I think the logs and Models zoo are more of a problem in terms of project size. Will be removing them as well. The code to download models and data is part of the project so shouldn't be a hassle to get these files.
